language: node_js
node_js:
  - 8

cache:
  directories:
  - node_modules
  - functions/node_modules

before_install:
  - chmod +x ./continuous_deployment/before_install.sh
  - ./continuous_deployment/before_install.sh

before_script:
  - npm test
  - chmod +x ./continuous_deployment/build.sh
  - travis_wait 40 ./continuous_deployment/build.sh

script:
  - chmod +x ./continuous_deployment/deploy.sh
  - travis_wait 40 ./continuous_deployment/deploy.sh

after_script:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - node node_modules/lighthouse-ci/runlighthouse.js https://react-most-wanted.com

  
