name: Integration Tests

on:
  push:
    branches: [main, umati]
  pull_request:
    branches: [umati, develop]

jobs:
  job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node: ['14', '16']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install yarn
        run: npm i -g yarn
      - name: Install packages
        run: npm ci --prefer-offline
      - name: Run integration tests
        run: npm run test:integration
