
name: BlackDuck Scan

on:
  # Triggers the workflow on push request events but only for the master branch
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Node runtime
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
      - name: Check WD 1 
        run: pwd      
      - name: Check Node 
        run: which node        
      - name: Check Node Version 
        run: node -v        
      - name: Check NPM 
        run: which npm        
      - name: Check NPM Version 
        run: npm -v         
      - name: Check Yarn 
        run: which yarn
      - name: Check yarn  
        run: yarn -v
        
      - name: Install cross-env  
        run: npm install cross-env
      
      - name: Install webpack
        run: npm install webpack
        
      - name: Install Chowkidar  
        run: npm install chokidar
      
      - name: Install babel 
        run: npm install -D babel-loader @babel/core @babel/preset-env webpack
        
      - name: Build with npm  
        run: npm install
              
          
      # -- Build your project here -- eg. mvn clean package
      # -- Build with steps and requirements 
      - name: Synopsys Detect
        uses: blackducksoftware/github-action@2.0.0
        with:
          args: '--blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.project.name="${{ secrets.PRODUCT}}" --detect.project.version.name="${{ secrets.VERSION}}" --detect.risk.report.pdf=true --detect.yarn.path=/usr/bin/yarn --detect.yarn.prod.only=true --detect.npm.path=/opt/hostedtoolcache/node/10.23.3/x64/bin/npm --detect.npm.include.dev.dependencies=false --detect.npm.arguments="\"npm install\"" --detect.excluded.detector.types="cpan,nuget,git,maven,lerna"'
      
      - name: Check WD  
        run: pwd      
      # Runs a set of commands using the runners shell
      - name: End of Scan
        run: |
          echo Finished scanning.    
